=== JiMWSnG/travel_weixin/src/main/resources/conf/RouteInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.tydic.com/VOP/route" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.tydic.com/VOP/route">
    <element name="routeConfigs">
    	<complexType>
    		<sequence>
    			<element name="routeConfig" minOccurs="0" maxOccurs="unbounded">
    				<complexType>
    					<sequence>
    						<element name="url" type="string" minOccurs="1" maxOccurs="1"></element>
    					</sequence>
    					<attribute name="systemKey" type="string" use="required"></attribute>
    				</complexType>
    			</element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== JiMWSnG/travel_weixin/src/main/resources/conf/RouteInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:routeConfigs xmlns:tns="http://www.tydic.com/VOP/route"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tydic.com/VOP/route RouteInfo.xsd ">
	<tns:routeConfig systemKey="vopDoor">
		<tns:url><![CDATA[http://127.0.0.1/pbox/services/VOPService]]></tns:url>
	</tns:routeConfig>
	<tns:routeConfig systemKey="vopResource">
		<tns:url><![CDATA[http://192.168.10.168:17126/RESMNG_S/services/VOPService]]></tns:url>
	</tns:routeConfig>
	<tns:routeConfig systemKey="VOPMNG_S">
		<tns:url><![CDATA[http://192.168.10.168:17116/VOPMNG_S/services/VOPService]]></tns:url>
	</tns:routeConfig>
	<tns:routeConfig systemKey="VOP_F">
		<tns:url><![CDATA[http://demo.tydic.com:9999/VOP_F/services/VOPService]]></tns:url>
	</tns:routeConfig>
	<tns:routeConfig systemKey="VOP_API">
		<tns:url><![CDATA[http://192.168.10.168:9702/OSN/services/VOPService]]></tns:url>
	</tns:routeConfig>
	<tns:routeConfig systemKey="VOP_ACCTMNG"><!-- 账管 -->
		<tns:url><![CDATA[http://192.168.10.168:9702/xxx/services/VOPService]]></tns:url>
	</tns:routeConfig>
</tns:routeConfigs>
